<?php
 $aik =  array (
  'sitename' => '智云影院',
  'pcdomain' => 'http://zhiyun.ppdsw.xyz/w/',
  'title' => '﻿智云影院-免VIP抢先观看最新好看的电影和电视剧',
  'keywords' => '智云影音影院,资源采集，最新影片资源采集，最新高清大片在线观看，电视直播网站,零八影院快播,高清云影视,云点播,免费看视频,湖南卫视直播,80电影网,最新电影天堂免费在线观看',
  'description' => '﻿智云影院,热剧快播,最好看的剧情片尽在﻿爱客影院,高清云影视免费为大家提供最新最全的免费电影，电视剧，综艺，动漫无广告在线云点播，以及电视直播',
  'icp' => '小提示：若等待15秒以上还未播放，请手动到首页切换其他播放源.加载需要时间.请耐心等待.高潮总在缓冲后!',
  'foot' => '本站提供的最新电影和电视剧资源均系收集于各大视频网站,本站只提供web页面服务,并不提供影片资源存储,也不参与录制、上传</br>若本站收录的节目无意侵犯了贵司版权，请给网页底部邮箱地址来信,我们会及时处理和回复,谢谢。',
  'tongji' => '<script language="javascript" type="text/javascript" src="http://js.users.51.la/18759442.js"></script>',
  'youlian' => '<a href="https://zhiyun.wodemo.net/entry/455642" target="_blank">精品资源</a>						<a href="https://jq.qq.com/?_wv=1027&k=5j71hMj" target="_blank">官方QQ群</a>	',
  'shouquan' => '公告：欢迎光临智云影音，更多精彩资源请关注官方发布信息，觉得好用请分享身边朋友！让本站走的更远！视频播放失败请更换线路或者源站',
  'zhanwai' => 'http://cj.zycjw1.com/inc/feifei3/',  
  'zhanwai1' => 'http://api.kbzyapi.com/inc/feifei3.4/',
  'zhanwai2' => 'http://cj.yongjiuzyw.com/inc/feifei3/',
  'zhanwai3' => 'http://cj.okzy.tv/inc/feifei3/',
  'zhanwai4' => 'http://cj.156zy.me/inc/feifei3/',
  'zhanwai5' => 'http://cj.131zy.net/inc/feifei3/',
  'zhanwai6' => 'http://cj.zuikzy.co/inc/feifei3/',
  'zhanwai7' => 'http://www.apizyp.com/inc/feifei3/',
  'zhanwai8' => 'http://cj.gaoqingzyw.com/inc/feifei3/',
  'zhanwai9' => 'https://cj.wlzy.tv/api/ffs/vod/',
  'zhanwai10' => 'http://cj.baiwanzy.com/inc/feifei3/',
  'zhanwai11' => 'http://api.zuixinapi.com/inc/feifei3/',
  'zhanwai12' => 'http://www.zdziyuan.com/inc/feifei3.4/',
  'jiekouyy' => 'http://jx.618g.com/?url=',
  'tvjx' => 'http://cj.zycjw1.com/inc/feifei3/?cid=12&p=1',
  'zyjx' => 'http://cj.zycjw1.com/inc/feifei3/?cid=3&p=1',
  'dmjx' => 'http://cj.zycjw1.com/inc/feifei3/?cid=4&p=1',
  'dyjx' => 'http://cj.zycjw1.com/inc/feifei3/?p=1',
  'zjx' => 'http://zy.bajieziyuan.com/inc/feifei3/',
  'admin_name' => 'admin',
  'admin_pass' => '3ceb0e9fb16f8673c35f707e8657124a',
  'admin_email' => '2248186422@admin.com',
  'logo_dh' => 'image/logo.png',
  'logo_ss' => './image/bg.jpg',
  'movie_ad' => '<img src="image/3.jpg" style="width:100%">',
  'tv_ad' => '<a href="http://zhiyun.ppdsw.xyz/w/" target="_blank"><img src="image/07.png" style="width:100%"></a>',
  'zongyi_ad' => '<a href="http://zhiyun.ppdsw.xyz/zb/" target="_blank"><img src="image/02.png" style="width:100%"></a>',
  'dongman_ad' => '<a href="http://zhiyun.ppdsw.xyz" target="_blank"><img src="image/07.png" style="width:100%"></a>',
    'rp_ad' => '<a href="http://zhiyun.ppdsw.xyz/w/" target="_blank"><img src="image/06.png" style="width:100%">',
  'bofang_ad' => '<a href="http://tao.uuhuo.cn" target="_blank"><img src="images/dc5c7986daef50c.gif" style="width:100%"></a>',
  'jiazai_ad' => '<a href="http://tao.uuhuo.cn" target="_blank"><img src="images/jiazai.png" width="100%"></a>',
  'tishi_ad' => '<style> 
 .black_overlay{  display: none;  position: absolute;  top: 0%;  left: 0%;  width: 100%;  height: 100%;  background-color: black;  z-index:1001;  -moz-opacity: 0.8;  opacity:.80;  filter: alpha(opacity=80);  }  .white_content {  display: none;  position: absolute;  top: 25%;  left: 25%;  width: 50%;   height: auto; padding: 16px;  border: 16px solid orange;  background-color: white;  z-index:1002;  overflow: auto;  }  </style> 
<a href="javascript:void(0)" onclick="document.getElementById(\'light\').style.display=\'block\';document.getElementById(\'fade\').style.display=\'block\'"><p style="text-align:center;color: #fff;font-size: 10px;background: #6ED56C;padding:11px 8px;border-radius: 2px;">点击关注“爱客影院”官方微信，看电影更方便!</p></a>
<div id="light" class="white_content"> 
  <img src="images/qrcode.png" width="100%" height="100%">
    <a href="javascript:void(0)" onclick="document.getElementById(\'light\').style.display=\'none\';document.getElementById(\'fade\').style.display=\'none\'"> 
    <span class="rewards-popover-close" etap="rewards-close"></span></a></div> 
<div id="fade" class="black_overlay"> 
</div> ',
  'dbts' => '【点击选择剧集才会播放哦！】',
  'zfb_ad' => '<img src="images/zfb.png">',
  'wx_ad' => '<img src="images/wx.png">',
  'cebian1_ad' => '<a class="style01" href="http://wpa.qq.com/msgrd?v=3&uin=3423135250&site=qq&menu=yes" target="_blank"><strong>源码出售</strong><h2>更好的视频主题</h2><p>1.扁平化、简洁风、多功能配置，优秀的电脑、平板、手机支持，响应式布局，不同设备不同展示效果...2.视频全自动采集，不需人工干预，懒人必备！</p></a>',
  'cebian2_ad' => '<a class="style02"  href="https://s.click.taobao.com/okHmscw" target="_blank"><strong>本站同款</strong></br></br><img src="images/aly.jpg"></a>',
  'cebian3_ad' => '',
  'cebian4_ad' => '',
  'top1_ad' => '<a href="app.html">客户端</a>',
  'top2_ad' => '',
  'top_ad' => '',
  'weixin_ad' => '<img src="images/qrcode.png">',
  'end_ad' => '<a href="yhq.php"><span><img src="images/gouwu.png"/>购物</span></a>',
  'dtk_ad' => 'http://tao.uuhuo.cn/',
  'qq_name' => '醉玲珑#无证之罪#权力的游戏第七季',
  'hometopnotice' => '',
  'hometopright' => '',
  'homelink' => '',
  'sort' => '1,2,3,4,5,6,7,8,9,10',
  'joinhotkey' => '0',
);
?>
